### PR TITLE
Patcher for 7.4.0 [PRO]

### PR DESCRIPTION
**Pull request by zeroryuki**
Pro features patch for v7.4.0 (latest)

### CODE REVIEW

**Review by Happin3ss — APPROVED** [review]
Verified work well with 7.4.0 !

**Comment by dj-nitehawk** [comment]
works like a charm on windows v7.4.0

**Comment by stenvix** [comment]
Verified work well with 7.4.0 !

**Comment by vladimirlv17** [comment]
Yes. It's work on Linux Kubuntu 18.04 with 7.4.0.

**Review by msgoon — APPROVED** [review]

**Comment by pinguet62** [comment]
👍 on Windows with 7.4.0

**Comment by kirillz** [comment]
Manjaro +1

**Comment by aeXuser264** [comment]
lol, i made my own before finding this pull request :sob: . And its almost same as urs.
It works tested on ubuntu 20.04. So, @5cr1pt pls merge this.

**Pull request merged**
