### PR TITLE
Fix findAsarWindows

### PR DESCRIPTION
**Pull request by BadClyx**
Here is a quick PR which fixes the findAsarWindows functions.
Because Gitkraken changed their directories naming, the old function wasn't able to find the correct path of the .asar file.

Note: Didn't tested it on Unix. Mac OS is ok.

### CODE REVIEW

**Comment by AlonsoK28** [comment]
**How I can use this fix to patch my GitKraken?**

Related to https://github.com/5cr1pt/GitCracken/issues/9

**Comment by BadClyx** [comment]
> **How I can use this fix to patch my GitKraken?**
> 
> Related to #9

Hi, simply clone this repository and edit the source with the modifications I made. Then build and run.

**Comment by AlonsoK28** [comment]
Working on Windows 10

**Hopefully as soon as possible this pull can be integrated into the project**

**Comment by Mike-Antipov** [comment]
Worked with 6.2.1 on Windows 7. I wonder if it is possible to turn off auto-updates.

**Comment by JourneyOver** [comment]
> Worked with 6.2.1 on Windows 7. I wonder if it is possible to turn off auto-updates.

I'm sure there is a way to turn off auto-updates but atm it's not really needed. This is still working on the newest 6.3.0 update that just released.

**Pull request merged**
